// contract test code will go here
const assert = require('assert');
const ganache = require('ganache-cli');
// Capital casing of W refers to constructor
const Web3 = require('web3');
//Lower casing of w refers to instace
const web3 = new Web3(ganache.provider());
const { interface, bytecode } = require('../compile');

//Variable that will hold the 10 random accounts generated by ganache.
let getAccounts;
//Variable that will hold our deployed contract on lines 21-23.
//This variable is our javaScript representation of the contract we deploy on lines 21-23.
let inbox;

beforeEach(async () => {
    // Get a list of all Accounts
    getAccounts = await web3.eth.getAccounts();

    //Use one of these contracts to deploy the contracts

    {/*The following lines of code are tied to the web3 library 
which is our sole means of intereacting with the ETH network. Our portal to Ethereum*/}
    inbox = await new web3.eth.Contract((JSON.parse(interface)))
        .deploy({ data: bytecode, arguments: ['Hi there!'] })
        .send({ from: getAccounts[0], gas: '1000000' });
});

describe('Inbox', () => {
    it('deploys a contract', () => {
        //ok method on assert insures that the value we pass in exists.
        assert.ok(inbox.options.address);
    });
});